name: firstapp
description: "مكانك الأفضل للمشاهدة"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  path_provider: ^2.1.4
  http: ^1.2.0
  shared_preferences: ^2.2.2
  video_player: ^2.8.2
  share_plus: ^10.0.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icon.png
  